config/routes.rb
Flixter::Application.routes.draw do

  devise_for :users
  resource :dashboard, :only => [:show]
  root 'static_pages#index'
  get 'privacy', :to => 'static_pages#privacy'
  resources :courses, :only => [:index, :show] do
    resources :enrollments, :only => :create
  end

  resources :lessons, :only => [:show]
  namespace :instructor do
    resources :lessons, :only => [:update]
    resources :sections, :only => [:update] do
      resources :lessons, :only => [:create]
    end
    resources :courses, :only => [:new, :create, :show] do
      resources :sections, :only => [:create]
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

end

app/controllers/instructor/courses_controller.rb
class Instructor::CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, :only => [:show]

  def new
    @course = Course.new
  end

  def create
    @course = current_user.courses.create(course_params)
    if @course.valid?
      redirect_to instructor_course_path(@course)
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def show
    @section = Section.new
    @lesson = Lesson.new
  end

  private

  def require_authorized_for_current_course
    if current_course.user != current_user
      render :text => "Unauthorized", :status => :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    @current_course ||= Course.find(params[:id])

  end


  def course_params
    params.require(:course).permit(:title, :description, :cost, :image)
  end

end

app/controllers/instructor/lessons_controller.rb
class Instructor::LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_section, :only => [:create]
  before_action :require_authorized_for_current_lesson, :only => [:update]

  def create
    @lesson = current_section.lessons.create(lesson_params)
    if @lesson.valid?
      redirect_to instructor_course_path(current_section.course)
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def update
    current_lesson.update_attributes(lesson_params)
    render :text => 'updated!'
  end


  private

  def current_lesson
    @current_lesson ||= Lesson.find(params[:id])
  end

  def require_authorized_for_current_section  #creating this method and making it a 'before action' removes it from methods.
    if current_section.course.user != current_user
      return render :text => 'Unauthorized', :status => :unauthorized
    end
  end

  def require_authorized_for_current_lesson
    if current_lesson.section.course.user != current_user
      return render :text => 'Unauthorized', :status => :unauthorized
    end
  end


  helper_method :current_section
  def current_section
    @current_section ||= Section.find(params[:section_id])
  end

  def lesson_params
    params.require(:lesson).permit(:title, :subtitle, :video, :row_order_position)
  end

end

app/controllers/instructor/sections_controller.rb
class Instructor::SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :require_authorized_for_current_course, :only => [:create]
  before_action :require_authorized_for_current_section, :only => [:update]


  def create
    @section = current_course.sections.create(section_params)
    if @section.valid?
      redirect_to instructor_course_path(current_course)
    else
      render :new, :status => :unprocessable_entity
    end
  end

  def update
    current_section.update_attributes(section_params)
    render :text => 'updated!'
  end


  private

  def current_section
    @current_section ||= Section.find(params[:id])
  end

  def require_authorized_for_current_section
    if current_section.course.user != current_user
      return render :text => 'Unauthorized', :status => :unauthorized
    end
  end

  def require_authorized_for_current_course
    if current_course.user != current_user
      return render :text => 'Unauthorized', :status => :unauthorized
    end
  end

  helper_method :current_course
  def current_course
    current_course ||= Course.find(params[:course_id])
  end

  def section_params
    params.require(:section).permit(:title, :row_order_position)
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructor/courses_helper.rb
module Instructor::CoursesHelper
end

app/helpers/instructor/lessons_helper.rb
module Instructor::LessonsHelper
end

app/helpers/instructor/sections_helper.rb
module Instructor::SectionsHelper
end

app/views/instructor/courses/new.html.erb
<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1>Add a new course</h1>
    <%= simple_form_for @course, :url => instructor_courses_path do |f| %>
    	<%= f.input :title %> <br />
   		<%= f.input :description %> <br />
    	<%= f.input :cost %> <br />
      <%= f.input :image %>
    	<br />
    	<%= f.submit "Create", :class => 'btn btn-primary' %>
    <br />
  	<% end %>
  <br />
</div>

app/views/instructor/courses/show.html.erb
<script>
  $(function() {
    $('.new-lesson-button').click(function(event) {
        var lessonUrl = $( event.target).data('lesson-url');
        $('#newLessonForm').attr('action', lessonUrl);
    });

    $('.lessons').sortable({      
      update: function( event, ui ) {
          $.ajax({
            type: 'PUT',
           url: ui.item.data('update-url'),
           dataType: 'json',
           data: { lesson: { row_order_position: ui.item.index() } }
          });
      }
    });
    $('.sections').sortable({      
      update: function( event, ui ) {
          $.ajax({
            type: 'PUT',
           url: ui.item.data('update-url'),
           dataType: 'json',
           data: { section: { row_order_position: ui.item.index() } }
          });
      }
    });


  });
</script>

<br />
<div class="booyah-box col-xs-10 col-xs-offset-1">
  <h1 class="text-center"><%= current_course.title %></h1>
    <%= image_tag current_course.image, :class => 'img-responsive' %>
	<br />

  <%= link_to 'Student view...', course_path(current_course), :class => 'btn btn-warning pull-right' %>
  
  <br class="clr" />

	<div class="text-center">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#newSectionModal">
      Add a new Section
    </button>
	</div>
  <ul class="sections">
    <% current_course.sections.rank(:row_order).each do |section| %>
      <li data-update-url= <%= instructor_section_path(section) %> class="section-li" >
        <div class="header">
          <span class="glyphicon glyphicon-list"></span>
          <%= section.title %>
        </div>
          <!-- Button trigger modal -->
          <button class="btn btn-primary btn-sm pull-right new-lesson-button" data-toggle="modal" data-target="#newLessonModal" data-lesson-url="<%=instructor_section_lessons_path(section) %>">
            New Lesson
          </button>
  
        <br class="clr" />
        <br class="clr" />
          <ul class="lessons">
          	<% section.lessons.rank(:row_order).each do |lesson| %>
              <li data-update-url= <%= instructor_lesson_path(lesson) %> >  <!-- This allows JS to access the update url-->
                <div class = "xs-col-1">
                </br />
                  <span class="glyphicon glyphicon-list"></span> 
                </div>
                <div class="col-xs-11 text-center">  
              	  <p>
                    <b><%= lesson.title %></b>
                	</p>
                  <p>
                	 <%= lesson.subtitle %>
                  </p>
                </div>
                <br class="clr" />
            	</li>
          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</div>


<!-- New Section Modal -->
<div class="modal fade" id="newSectionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="newSectionModalLabel">Add a new Section...</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @section, :url => instructor_course_sections_path(current_course) do |f| %>
          <%= f.input :title %> <br />
          <br />
          
          <br />
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Add a section", :class => 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<!-- New Lesson Modal -->
<div class="modal fade" id="newLessonModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="newLessonModal">Add a Lesson</h4>
      </div>
      <div class="modal-body">
         <%= simple_form_for @lesson, :url => "#", :html => {:id => 'newLessonForm' } do |f| %>
          <%= f.input :title %>
          <br />
          <%= f.input :subtitle %>
           <br />
          <%= f.input :video %>
          <br />
          
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "Add the lesson", :class => 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>